services:
  postgres: 
    hostname: ${POSTGRES_HOST}
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - backend
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432 # TODO: Don't forward port in production

  api:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - DATABASE_URL=${DATABASE_URL}
      - API_PORT=${API_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
    depends_on:
      - postgres
    networks:
      - backend
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}

volumes:
  pgdata:

networks:
  backend:
    name: ${NETWORK_NAME}
